plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.ggsalas.noticiosoandroid.feedrefresh'
version = ''

android {
  namespace "com.ggsalas.noticiosoandroid.feedrefresh"
  defaultConfig {
    versionCode 1
    versionName ""
  }
  lintOptions {
    abortOnError false
  }
}
